services:
  db:
    image: postgres:17-alpine
    container_name: uptime_database_container
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: uptime_db_local
      POSTGRES_USER: uptime
      POSTGRES_PASSWORD: pass123
    ports:
      - "5432:5432"
    volumes:
      - uptime_db_volume:/var/lib/postgresql/data
volumes:
  uptime_db_volume: