
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewbkurucdynoypfkpemf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3Ymt1cnVjZHlub3lwZmtwZW1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MDQyNzksImV4cCI6MjA1OTI4MDI3OX0.guIYzMO9fxJ-Ezd6RV8LC0U4ptGMbhmaqNU5Uysi-2M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
