#!/bin/bash

#Install jq
echo "Installing jq"
yum install -y jq

# Path to the JSON file
TABLES_FILE="/data/tables.json"

# Loop through each table in the JSON array
jq -c '.[]' $TABLES_FILE | while read -r table; do
  echo "Creating table from definition: $table"

  # Create a temporary file for the individual table JSON
  echo "$table" > /tmp/tables.json

  # Use AWS CLI to create the table
  aws dynamodb create-table --cli-input-json file:///tmp/tables.json --endpoint-url http://localstack:4566

  # Check the exit code of the AWS CLI command
  if [ $? -eq 0 ]; then
    echo "Table created successfully!"
  else
    echo "Failed to create table."
  fi

  # Clean up temporary file
  rm /tmp/tables.json
done
