AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB for activations used by the discount service'
Parameters:
  BillingMode:
    Default: PAY_PER_REQUEST
    Type: String

  IdAttributeName:
    Type: String
    Default: id
  IdAttributeType:
    Type: String
    Default: S

  IdentificationAttributeName:
    Type: String
    Default: identification
  IdentificationAttributeType:
    Type: String
    Default: S

  AccountIdAttributeName:
    Type: String
    Default: accountId
  AccountIdAttributeType:
    Type: String
    Default: S

Resources:
  database:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub ${AWS::StackName}
      BillingMode: !Ref 'BillingMode'
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: !Ref 'IdAttributeName'
          AttributeType: !Ref 'IdAttributeType'
        - AttributeName: !Ref 'IdentificationAttributeName'
          AttributeType: !Ref 'IdentificationAttributeType'
        - AttributeName: !Ref 'AccountIdAttributeName'
          AttributeType: !Ref 'AccountIdAttributeType'
      KeySchema:
        - AttributeName: !Ref 'AccountIdAttributeName'
          KeyType: HASH
        - AttributeName: !Ref 'IdAttributeName'
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: asset_identification
          KeySchema:
            - AttributeName: !Ref 'IdentificationAttributeName'
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: asset_asset_id
          KeySchema:
            - AttributeName: !Ref 'IdAttributeName'
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true

Outputs:
  TableName:
    Value: !Ref database
    Description: Table name of the newly created DynamoDB table
    Export:
      Name: !Sub ${AWS::StackName}-tableName
  TableArn:
    Value: !GetAtt database.Arn
    Description: Arn of the newly created DynamoDB table
    Export:
      Name: !Sub ${AWS::StackName}-table-arn