-- Migration para criar tabelas do sistema de Worklog Kanban
-- Task: feat/16764 - Worklog Kanban

-- Tabela principal para logs de alteração de etapas no Kanban
CREATE TABLE WORKLOG_KANBAN (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    OCCURRENCE_ID INT NOT NULL,
    OCCURRENCE_UUID VARCHAR(255) NOT NULL,
    STEP VARCHAR(50) NOT NULL,
    PREVIOUS_STATUS VARCHAR(50),
    NEW_STATUS VARCHAR(50) NOT NULL,
    USER_ID VARCHAR(255) NOT NULL,
    USER_UUID VARCHAR(255),
    USER_NAME VARCHAR(255),
    CHANGED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ACTION_TYPE VARCHAR(50) NOT NULL,
    DESCRIPTION TEXT
);

-- Tabela para logs de alteração de campos específicos
CREATE TABLE WORKLOG_FIELD_CHANGE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    WORKLOG_KANBAN_ID BIGINT NOT NULL,
    FIELD_NAME VARCHAR(255) NOT NULL,
    OLD_VALUE TEXT,
    NEW_VALUE TEXT,
    FIELD_TYPE VARCHAR(50),
    CHANGED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (WORKLOG_KANBAN_ID) REFERENCES WORKLOG_KANBAN(ID) ON DELETE CASCADE
);

-- Índices para otimização de consultas
CREATE INDEX WORKLOG_KANBAN_OCCURRENCE_IDX ON WORKLOG_KANBAN(OCCURRENCE_ID);
CREATE INDEX WORKLOG_KANBAN_USER_IDX ON WORKLOG_KANBAN(USER_ID);
CREATE INDEX WORKLOG_KANBAN_DATE_IDX ON WORKLOG_KANBAN(CHANGED_AT);
CREATE INDEX WORKLOG_FIELD_WORKLOG_IDX ON WORKLOG_FIELD_CHANGE(WORKLOG_KANBAN_ID);
CREATE INDEX WORKLOG_FIELD_FIELD_IDX ON WORKLOG_FIELD_CHANGE(FIELD_NAME);

-- Comentários para documentação
COMMENT ON TABLE WORKLOG_KANBAN IS 'Registra logs de alteração de etapas no Kanban';
COMMENT ON TABLE WORKLOG_FIELD_CHANGE IS 'Registra logs de alteração de campos específicos';

COMMENT ON COLUMN WORKLOG_KANBAN.STEP IS 'Etapa atual da ocorrência';
COMMENT ON COLUMN WORKLOG_KANBAN.PREVIOUS_STATUS IS 'Status anterior da etapa';
COMMENT ON COLUMN WORKLOG_KANBAN.NEW_STATUS IS 'Novo status da etapa';
COMMENT ON COLUMN WORKLOG_KANBAN.ACTION_TYPE IS 'Tipo de ação: STEP_CHANGE, FIELD_UPDATE, CARD_MOVED';
COMMENT ON COLUMN WORKLOG_FIELD_CHANGE.FIELD_TYPE IS 'Tipo do campo: STRING, NUMBER, DATE, BOOLEAN, JSON';
