// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjjpocflfbzwrqjcchie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqanBvY2ZsZmJ6d3JxamNjaGllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MTIyOTcsImV4cCI6MjA2MTE4ODI5N30.LOTmiUv3AnS0Wyysz_WWTiN9qP-FMxS1nIHrIk3PSSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);